schema_version: 1

context:
  name: ldas-tools-al
  version: "2.10.0"
  # dependencies
  ldas_tools_cmake_version: 1.5.0

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: http://software.ligo.org/lscsoft/source/${{ name }}-${{ version }}.tar.gz
  sha256: 698d1061c7ec416476400459b98bd74ef67646c72f28b5c6eabd6a27127e43e6
  patches:
    # when cross-compiling without an emulator disable some checks that use try_run
    # see https://git.ligo.org/ldastools/LDAS_Tools/-/issues/117
    - if: osx and arm64
      then: no-check-procfs.patch

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
    - cmake >=3.6
    - make
    - pkg-config
  host:
    - ldas-tools-cmake >=${{ ldas_tools_cmake_version }}
    - libboost-devel
  run_exports:
    - ${{ pin_subpackage("ldas-tools-al", upper_bound="x.x") }}

tests:
  - package_contents:
      lib:
        - ldastoolsal
      include:
        - ldastoolsal/ldas_types.h
  - requirements:
      run:
        - pkg-config
    script:
      - pkg-config --print-errors --exact-version ${{ version }} ldastoolsal

about:
  summary: LDAS tools abstraction toolkit
  homepage: https://wiki.ligo.org/Computing/LDASTools
  repository: https://git.ligo.org/ldastools/LDAS_Tools
  license: GPL-2.0-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - duncanmmacleod
    - emaros
