schema_version: 1

context:
  name: ldas-tools-al
  version: "2.10.1"
  # dependencies
  ldas_tools_cmake_version: 1.5.0

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: http://software.ligo.org/lscsoft/source/${{ name }}-${{ version }}.tar.gz
  sha256: 06a740f5ca9c6fdc3dd58a254051070744776f2c68e58f22bc0724ee4f2895c1

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
    - cmake >=3.12,<4.0.0a0
    - make
    - pkg-config
  host:
    - ldas-tools-cmake >=${{ ldas_tools_cmake_version }}
    - libboost-devel
  run_exports:
    - ${{ pin_subpackage("ldas-tools-al", upper_bound="x.x") }}

tests:
  - package_contents:
      lib:
        - ldastoolsal
      include:
        - ldastoolsal/ldas_types.h
  - requirements:
      run:
        - pkg-config
    script:
      - pkg-config --print-errors --exact-version ${{ version }} ldastoolsal

about:
  summary: LDAS tools abstraction toolkit
  homepage: https://wiki.ligo.org/Computing/LDASTools
  repository: https://git.ligo.org/ldastools/LDAS_Tools
  license: GPL-2.0-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - duncanmmacleod
    - emaros
